/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int ELSE = 11;
  int EXTENDS = 12;
  int FALSE = 13;
  int IF = 14;
  int IMPORT = 15;
  int INSTANCEOF = 16;
  int INT = 17;
  int FLOAT = 18;
  int DOUBLE = 19;
  int NEW = 20;
  int NULL = 21;
  int PACKAGE = 22;
  int PRIVATE = 23;
  int PROTECTED = 24;
  int PUBLIC = 25;
  int RETURN = 26;
  int STATIC = 27;
  int SUPER = 28;
  int THIS = 29;
  int TRUE = 30;
  int VOID = 31;
  int WHILE = 32;
  int FOR = 33;
  int ENHANCEDFOR = 34;
  int IMPLEMENTS = 35;
  int FINAL = 36;
  int PLUS = 37;
  int ASSIGN = 38;
  int DEC = 39;
  int EQUAL = 40;
  int GT = 41;
  int INC = 42;
  int LAND = 43;
  int LE = 44;
  int LNOT = 45;
  int MINUS = 46;
  int PLUS_ASSIGN = 47;
  int STAR = 48;
  int LPAREN = 49;
  int RPAREN = 50;
  int LCURLY = 51;
  int RCURLY = 52;
  int LBRACK = 53;
  int RBRACK = 54;
  int SEMI = 55;
  int COMMA = 56;
  int DOT = 57;
  int COL = 58;
  int IDENTIFIER = 59;
  int LETTER = 60;
  int DIGIT = 61;
  int NON_ZERO_DIGIT = 62;
  int INT_LITERAL = 63;
  int CHAR_LITERAL = 64;
  int STRING_LITERAL = 65;
  int DOUBLE_LITERAL = 66;
  int FLOAT_LITERAL = 67;
  int ESC = 68;
  int ERROR = 69;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"float\"",
    "\"double\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"for\"",
    "\"enhanced for\"",
    "\"implements\"",
    "\"final\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<FLOAT_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
